events {}

http {
    server {
        listen 443 ssl default_server;
        server_name _ localhost yeonjuki.42.fr;

        ssl_certificate /root/.tls/server.crt;
        ssl_certificate_key /root/.tls/server.key;

        root /var/www/html;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?q=$uri&$args;
        }
        include  /etc/nginx/mime.types;

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param HTTP_HOST $http_host;
            fastcgi_param HTTPS $https;
            fastcgi_param SERVER_PORT $server_port;
            fastcgi_param REQUEST_SCHEME $scheme;
            fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;
        }

        location ~ \.css {
            add_header  Content-Type    text/css;
        }

        location ~ \.js {
            add_header  Content-Type    application/x-javascript;
        }
    }
}
