events {}

http {
    server {
        listen 80;
        server_name yeonjuki.42.fr;

        return 301 https://$server_name;
    }

    server {
        listen 443 ssl;
        server_name yeonjuki.42.fr;

        ssl_certificate /root/.tls/server.crt;
        ssl_certificate_key /root/.tls/server.key;

        root /var/www/html;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?q=$uri&$args;
        }
        include  /etc/nginx/mime.types;

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
        }

        location ~ \.css {
            add_header  Content-Type    text/css;
        }

        location ~ \.js {
            add_header  Content-Type    application/x-javascript;
        }
    }
}
