services:
  nginx:
    container_name: inception-nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: inception-nginx

    networks:
      - inception
    ports:
      - 80:80
      - 443:443
    volumes:
      - wp-volume:/var/www/html

    restart: always
    
  wordpress:
    container_name: inception-wordpress
    image: wordpress:php8.1-fpm
    # build:
    #   context: ./requirements/wordpress
    #   dockerfile: Dcokerfile
    # image: inception-wordpress

    # image: wordpress

    networks:
      - inception
    ports:
      - 3306
      - 9000
    volumes:
      - wp-volume:/var/www/html

    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
      WORDPRESS_TABLE_PREFIX: wp_

    restart: always

  mariadb:
    container_name: inception-mariadb
    # build:
    #   context: ./requirements/mariadb
    #   dockerfile: Dockerfile
    # image: inception-mariadb
    image: mariadb

    networks:
      - inception
    ports:
      - 3306
    volumes:
      - db-volume:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PW}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PW}

    restart: always

volumes:
  db-volume:
    driver: local
    driver_opts:
      device: /home/yeonjuki/data/db-data
      type: none
      o: bind

  wp-volume:
    driver: local
    driver_opts:
      device: /home/yeonjuki/data/wp-data
      type: none
      o: bind


networks:
  inception:
    name: inception
    driver: bridge
