services:
  nginx:
    container_name: inception-nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: inception-nginx

    networks:
      - inception
    ports:
      - 80:80
      - 443:443
    volumes:
      - wp-volume:/var/www/html

    restart: always

    # depends_on:
    #   - wordpress
    
  wordpress:
    container_name: inception-wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        WORDPRESS_VERSION: ${WP_VERSION}
    image: inception-wordpress

    networks:
      - inception
    ports:
      - 3306
      - 9000
    volumes:
      - wp-volume:/var/www/html

    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      # Use the same DB user/password/database as the mariadb service below
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PW}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_VERSION: ${WP_VERSION}

    restart: always

  mariadb:
    container_name: inception-mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: inception-mariadb

    networks:
      - inception
    ports:
      - 3306
    volumes:
      - db-volume:/var/lib/mysql

    environment:
      # Root password (for root user)
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PW}

    restart: always

volumes:
  db-volume:
    driver: local
    driver_opts:
      device: ${DB_VOLUME}
      type: none
      o: bind

  wp-volume:
    driver: local
    driver_opts:
      device: ${WP_VOLUME}
      type: none
      o: bind


networks:
  inception:
    name: inception
    driver: bridge
