services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: inception-nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    
  # wordpress:
  #   build:
  #     context: ./requirements/wordpress
  #     dockerfile: Dcokerfile
  #   image: inception-wordpress
  #   ports:
  #     - 3306
  #     - 9000

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: inception-mariadb
    ports:
      - 3306
