[Global]
Name = inception.irc
Info = IRC server for inception
AdminInfo1 = Admin
Listen = 0.0.0.0
Ports = 6667

[Options]
PAM = no
Ident = no
NoticeAuth = yes

[Operator]
Name = admin
Password = password
Mask = *@*
